name: krl_goon
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'
  # sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  pinput: ^3.0.1
  provider: ^6.1.1
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  intl_phone_number_input: ^0.7.4
  loading_animation_widget: ^1.2.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/images/

